module.exports = {
    rules: {
        "react/boolean-prop-naming": "error",
        "react/hook-use-state": ["error", { allowDestructuredState: true }],
        "react/no-danger": "error",
        "react/jsx-fragments": "error",
        "react/no-unsafe": "error",
        "react-hooks/exhaustive-deps": "warn",
        "unicorn/no-await-expression-member": "off",
        "unicorn/prefer-module": "off",
        "react/no-children-prop": "off",
        "react/jsx-no-target-blank": ["error", { "enforceDynamicLinks": "never" }],
        "unicorn/prefer-dom-node-text-content": "off",
        "unicorn/no-array-reduce": "off",
        "react/prop-types": 0,
        "guard-for-in": 2,
        "no-shadow": "off",
        "@typescript-eslint/no-shadow": "off",
        "no-bitwise": "error",
        "no-console": [2, { allow: ["warn", "error"] }],
        "@typescript-eslint/no-dynamic-delete": 2,
        "no-empty": 2,
        "@typescript-eslint/no-misused-new": 2,
        "default-case": 2,
        "no-return-await": 2,
        "object-shorthand": [2, "always"],
        "import/order": [
            "error",
            {
                groups: ["builtin", "external", "internal", "parent", "sibling", "unknown"],
                "newlines-between": "always",
            },
        ],
    },
};
