name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@master
      with:
          node-version: ${{ matrix.node-version }}
    - uses: actions/checkout@v3
    - name: Install dependencies
      run:
          npm install
          npm ci 
      # build and test the apps     
    - name: build
      run: |
          npm run build
    - name: Login to Docker hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo:latest
          
    - name: Run the image in a container
      uses: addnab/docker-run-action@v3
      with:
            image: ${{ secrets.DOCKER_HUB_USERNAME }}/nodejs-demo:latest
            run: |
              echo "runing the docker image"
              echo "Testing the nodejs  app endpoints"
              echo ${{ steps.docker_build.outputs.digest }}
