name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@master
      with:
          node-version: ${{ matrix.node-version }}
    - uses: actions/checkout@v3
    - name: Install dependencies
      run:
          npm install
          npm ci 
    - name: Login to Docker hub
      env: 
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag eventsproject/events:${{ github.sha }}
    - name: Docker push
      run: docker push eventsproject/events:${{ github.sha }}
